
<form  method ="POST">
<nav id ="searchStudent">
	<div id="container"> 
		<h1>Add Block Section Subject</h1>

		<h3 id="input"></h3>
		<input id="subjectID"  type="text" name="subjectID" "  /> subject_id<br/>
		<input id="blockSection" type="text" name="blockSection" "  /> Block Section<br/>
		<input id="semesterNumber" type="text" name="semesterNumber" "  /> Semester Number<br/>
		
		<input class="btn" id="button_save" type="submit" name="save" value="save" />		
		<a style="float:right" href="/blocksection">(Return)</a>
	</div>
</nav>	
</form>


