
<script src="/j	/admin.js"></script>

	<form>
		<a style="float:left" href="/index">(Return)</a>
		<a class="pull-right btn btn-success" 
			href="/blocksection/add">
		<i class="glyphicon glyphicon-plus"></i></a>
	</form>
		<div id="subjects-pagination" class="pagination">
		  <ul>
		    <li><a href="/blocksection/index?page=<?php echo $this->currentPage <= 1?1:$this->currentPage-1; ?>">Prev</a></li>
		    <?php for ($pageNumber = 1; $pageNumber <= BlockSection::getNumberOfPages($this->blockSectionCount); $pageNumber++) { ?>
		    	<li class="<?php echo ($pageNumber == $this->currentPage)?'active':'';?>"><a href="/blocksection/index?page=<?php echo $pageNumber; ?>"><?php echo $pageNumber; ?></a></li>
		    <?php } ?>
		    <li><a href="/blocksection/index?page=<?php echo ($this->currentPage >= BlockSection::getNumberOfPages($this->blockSectionCount))?$this->currentPage:$this->currentPage+1; ?>">Next</a></li>
		  </ul>
		</div>
	<div class="col-md-6">
		<table class="table table-bordered table-condensed table-striped table-inverse">
			
			<tr>
				<th>subect_id</th>
				<th>block_section</th>
				<th>semester_number</th>
				<th>Details</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
				<?php foreach ($this->blockSection as $details):?>
				<tr>
				<td align="center"><?php echo $details['subject_id']; ?></td>
				<td align="center"><?php echo $details['block_section']; ?></td>
				<td align="center"><?php echo $details['semester_number']; ?></td>
				<td>	
					<a 
						onclick="viewDetails(<?php echo $details['user_id']; ?>);" 
						class="btn" 
						title="edit Student"
						data-toggle="modal" data-target="#admin-details"> 
						<i class="glyphicon glyphicon-search"></i>
					</a>
				</td>
				<td style="width: 1px; wrap: nowrap;">
					<a href="/blocksection/edit?subjectID=<?php echo $details['subject_id']; ?>&blockSection=<?php echo $details['block_section']; ?>&semesterNumber=<?php echo $details['semester_number'];?>" 
				   		class="btn" 
				   		title="edit blocksection"> 
				   		<i class="glyphicon glyphicon-edit"></i>
					</a>
				</td>					
				<td style="width: 1px; wrap: nowrap;">			
					<a href='/blocksection/delete?subjectID=<?php echo $details['subject_id']; ?>&blockSection=<?php echo $details['block_section']; ?>&semesterNumber=<?php echo $details['semester_number']; ?>' 
						class="btn btn-danger" title="blocksection"> 
						<i class="glyphicon glyphicon-remove"></i>
					</a>
				</td>

				</tr>
			<?php endforeach;?>
		</table>	
	 </div>
	

<div id="blockSection-details" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Admin Details</h4>
      </div>
      <div class="modal-body">
        <dl>
        	<dt>subjectID</dt><dd id="adminID"></dd>
        	<dt>Block Section</dt><dd id="adminUser"></dd>
        	<dt>Semeter Number</dt><dd id="adminPass"></dd>
        </dl>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal"><i class="icon icon-remove"></i></button>
      </div>
    </div>

  </div>
</div>



	

