

	<h1>School Overview</h1>
<?php 
	if (Zend_Registry::get('config')->debug) {
		Zend_Debug::dump($_SESSION); 
	}
?>
	  <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="/img/school1.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>This is top view of the School University</h1>
              <p></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="/img/school2.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>This is the main Building of the School University</h1>
              <p></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="/img/school3.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>This are the student of the School University</h1>
              <p></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

  <footer>
  <center>
    <div class="fb-follow" data-href="<?php echo $this->url; ?>" data-width="200px" data-layout="standard" data-size="large" data-show-faces="true"></div>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1729933903964760";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
    <div class="fb-like" 
        data-href="http://sample.enrollment.com/index.phtml" 
        data-layout="standard" 
        data-action="like" 
        data-show-faces="true">
    </div>
    <div class="fb-share-button" 
        data-href="http://sample.enrollment.com/index.phtml" 
        data-action="share"
        data-layout="button_count">
      </div>
      <div class="fb-comments" 
        data-href="http://sample.enrollment.com/index.phtml" 
        data-numposts="5">    
      </div>
    <a href="https://twitter.com/intent/tweet?button_hashtag=LoveTwitter" 
    class="twitter-hashtag-button" data-show-count="false">Tweet #LoveTwitter</a>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
  </center>
   <script src="https://apis.google.com/js/platform.js" async defer>
    </script>

   <div data-callback="subscribeGooglePlusOne" 
    data-href="https://omnithopter.000webhostapp.com/index.php" 
    data-size="medium" class="g-plusone">
   </div>

   
</footer> 
