
<form  method ="POST">
<nav id ="searchStudent">
	<div id="container"> 
		<h1>Add Block Section </h1>

		<h3 id="input"></h3>
		<input id="bSection" type="text" name="bSection" "  /> Block Section<br/>
		<input id="semesterNumber" type="text" name="semesterNumber" "  /> Semester Number<br/>
		
		<input class="btn" id="button_save" type="submit" name="save" value="save" />		
		<a style="float:right" href="/bsection">(Return)</a>
	</div>
</nav>	
</form>


