<script src="/js/bsection.js"></script>
	<h1>Block Section Records</h1>
	<div class="col-md-6">
		<a style="float:left" href="/index">(Return)</a>
		<a class="pull-right btn btn-success" 
			href="/bsection/add">
		<i class="glyphicon glyphicon-plus"></i></a>
				
		<table id="bSectionSubjectMatchTable" class="table table-bordered table-condensed table-striped">
		<thead class="tHeader">	
			<tr>
				<th>Block Section ID</th>
				<th>Block Section</th>
				<th>Semester Number</th>				
				<th>Number Of Subject</th>				
				<th>Details</th>
				<th>DeleteSubjects</th>
				<th>edit </th>
				<th>delete</th>
			</tr>
		</thead>	
				<?php foreach ($this->bSection as $details):?>
			<tr>
				<td align="center"><?php echo $details['bsection_id']; ?></td>
				<td align="center"><?php echo $details['bsection']; ?></td>
				<td align="center"><?php echo $details['semester_number']; ?></td>
				<td align="center"><?php echo $details['total']; ?></td>
				<td style="width: 1px; wrap: nowrap;">	
					<a  
						onclick="bSectionID(<?php echo $details['bsection_id']; ?>);viewBSectionDetails(<?php echo $details['bsection_id']; ?>);totalUnits(<?php echo $details['bsection_id']; ?>);"
						id = "blockSectionDetailsButton" 
						class="btn" 
						title="View Block Section"
						data-toggle="modal" data-target="#bSection-details"> 
						<i class="glyphicon glyphicon-search"></i>
					</a>
				</td>	
				<td style="width: 1px; wrap: nowrap;">	
					<a  
						onclick="deletebSectionSubjects(<?php echo $details['bsection_id']; ?>);"
						id = "blockSectionDetailsButton" 
						class="btn btn-danger" 
						title="View Block Section"
						data-toggle="modal" data-target="#bSection-delete"> 
						<i class="glyphicon glyphicon-remove"></i>
					</a>
				</td>	
				<td style="width: 1px; wrap: nowrap;">	
					<a 
						href="/bsection/edit?bSectionID=<?php echo $details['bsection_id']; ?>" 
				   		class="btn" 
				   		title="edit blocksection"> 
				   		<i class="glyphicon glyphicon-edit"></i>	
					</a>
				</td>					
				<td style="width: 1px; wrap: nowrap;">			
					<a 
						href='/bsection/delete?bSection=<?php echo $details['bsection']; ?>&semesterNumber=<?php echo $details['semester_number']; ?>' 
						class="btn btn-danger" title="blocksection"> 
						<i class="glyphicon glyphicon-remove"></i>
					</a>
				</td>	

			</tr>
			<?php endforeach;?>
		</table>	
	</div>	
	<div class="col-md-6">
		<h1>
			<label class="label label-info">This is where you can view, edit, delete <br></br> blocksection  and can add, delete <br></br> blocksection subjects </label>
		</h1>
	</div>
<div id="bSection-details" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" >
        <h4 class="modal-title "  >Block Section Details</h4>
      </div>
    <div class="modal-body">
		<div class = "blocksection">
			
		 </div>

		   <dl>
		        	<dt>totalUnits</dt><dd id="totalUnits"></dd>
		        </dl>
		        <label> list of subject you one to add</label>
			<select class="listsubject" name="getSubjectID" onchange="checkSubjectAdd();">		
				
			</select>	
		        <label id = "labelAddSubject">Subject That will Be Added</label>
			<div class = "addSubjectsTable">
		<table id = "addTableData" class="table table-bordered table-condensed table-striped">

			<tr>
				<th>Block Section ID</th>
				<th>Subject ID</th>
				<th>Subjects</th>
			</tr>

		</table>
			</div>

	 </div>	
      <div class="modal-footer">
       	<!--<button data-dismiss="modal" class="btn btn-default" id="button_save" type="submit" name="edit" value="save" onclick="addSubjects()">save</button>-->
       	<button id="bs" data-dismiss="modal" class="btn btn-default"  type="submit" name="save" value="save">save</button>
		<button type="button" class="btn btn-default btn-danger" data-dismiss="modal">	<i class="glyphicon glyphicon-remove"></i></button>
      </div>
    </div>

  </div>
</div>

<div id="bSection-delete" class="modal fade" role="dialog">

	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 class="modal-title">Student Add</h4>
	      </div>
	      <div class="modal-body">
	      		<div class = "deletebSectionIDSubjectID">
		
	 			</div>
	 		<label> list of subject you one to Delete</label>
				<select class="deleteblocksection" name="getSubjectID" onchange="checkSubjectDelete();">		
				
				</select>		
				  <label id = "labelAddSubject">Subject That will Be delleted</label>
			<div class = "addSubjectsTable">
		<table id = "deleteTableData" class="table table-bordered table-condensed table-striped">

			<tr>
				<th>Block Section ID</th>
				<th>Subject ID</th>
				<th>Subjects</th>
			</tr>

		</table>
			</div>
		    

	      </div>
	      <div class="modal-footer">
   			<button id="bSDelete" data-dismiss="modal" class="btn btn-default"  type="submit" name="delete" value="delete">delete</button>
	        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal">	<i class="glyphicon glyphicon-remove"></i></button>
	      </div>
	    </div>

	  </div>
	
</div>

