
<iframe src="<?php echo $this->url; ?>" width="200px"></iframe>

<div class="fb-follow" data-href="<?php echo $this->url; ?>" data-width="200px" data-layout="standard" data-size="large" data-show-faces="true"></div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1729933903964760";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>


<script type='text/javascript' src='/js/student_enroly.js'></script>
<script type='text/javascript' src='/js/studentGrade.js'></script>
  <script src="/js/studentSubject.js"></script>

 
<button id = "sunday">Show href Value</button>
<button id = "hide"> click me to hide  Table and navbar and remove paragraph</button></br>
<button id = "show">click me to show Table and navbar</button>
<button onclick="appendText()">Append Text</button></br>
<button id="animation"> Start Animation </button>

<p id="test"> This is some <b>bold</b> text in paragrap</p>
<p id="test1"s>This is a Paragraph Thi</p>
<p id="test2"> This is another Paragraph </p>
<div id ="box" style="background: #98bf21;height:100px;width:100px;position:absolute;"></div>
<p><a href="http://www.google.com" id="dogy">Google.com</a></p>