<link type="text/css" rel="stylesheet" href="../../../../css/signup.css" />

<div id="container">
  <form action="/signup/index" Method="POST">
    <div class="alert alert-danger">
      <?php if (!empty($this->students['error'])): ?>
        <div>
          <?php echo $this->students['error']; ?>
        
        </div>
      <?php endif; ?>
    </div>   
    <div name="signUp" id="signUp">
      <label><b>Email</b></label>
      <input type="email" placeholder="Enter Email" name="email" value="<?php echo isset($_POST['email']) ? $_POST['email'] : '' ?>"  required >
    
      <label><b>Name</b></label>
      <input type="text" placeholder="Enter Name" name="name" value="<?php echo isset($_POST['name']) ? $_POST['name'] : '' ?>"  required >
    
      <label><b>Last Name</b></label>
      <input type="text" placeholder="Enter Last Name" name="lastname" value="<?php echo isset($_POST['lastname']) ? $_POST['lastname'] : '' ?>" required >


      <label><b>User</b></label>
      <input type="text" placeholder="Enter User" pattern=".{8,12}" required title="8 to 12 characters" name="user" value="<?php echo isset($_POST['user']) ? $_POST['user'] : '' ?>" required >

      <label><b>Password</b></label>
      <input type="password" placeholder="Enter Password" pattern=".{8,12}" required title="8 to 12 characters" name="psw" value="<?php echo isset($_POST['psw']) ? $_POST['psw'] : '' ?>"  required >

      <label><b>Repeat Password</b></label>
      <input type="password" placeholder="Repeat Password" pattern=".{8,12}" required title="8 to 12 characters" name="psw-repeat" value="<?php echo isset($_POST['psw-repeat']) ? $_POST['psw-repeat'] : '' ?>"  required >
      <input type="checkbox" checked="checked"> Remember me

      <div class="clearfix">
        <button type="button"  class="cancelbtn"><a href="/login/" >Cancel</a> </button>
        <button type="submit" class="signupbtn" name="save">Sign Up</button>
      </div>
    </div>
  </form>
</div>