
<form  method ="POST">
<nav id ="searchStudent">
	<div id="container"> 
		<h1>Add Subject ID and Block Section ID</h1>

		<h3 id="input"></h3>
		<input id="bSectionID" type="text" name="bSectionID" "  /> Enter Block Section ID<br/>
		<input id="subjectID" type="text" name="subjectID" "  /> Enter Subject ID<br/>
		
		<input class="btn" id="button_save" type="submit" name="save" value="save" />		
		<a style="float:right" href="/bsectionsubject">(Return)</a>
	</div>
</nav>	
</form>


