
<script type="text/javascript" src="/js/students.js"></script>

<form method = "post" action="/login/login">
    

     <!--
    you can substitue the span of reauth email for a input with the email and
    include the remember me checkbox
 
    -->
    <div class="container">
        <div class="card card-container">
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
            <p id="profile-name" class="profile-name-card"></p>
                <span id="reauth-email" class="reauth-email"></span>
              <input type = "text" class = "form-control" name = "username" placeholder = "username" required autofocus></br>
              <input type = "password" class = "form-control" name = "password" placeholder = "password" required autofocus>
             <button  class = "btn btn-primary btn-block login" type = "submit" 
              name = "login">Login</button><br/>
          <label>
              <input type="checkbox" value="remember-me"> Remember me
          </label>
          <table class=" table table-bordered table-condensed table-striped">    
            <tr><td><a  href="<?php echo $this->fbloginurl; ?>&loginType=facebook" class="btn btn-primary btn-block login">Facebook Login</a></td></tr> 
            <tr><td><a href="<?php echo $this->googleLoginUrl; ?>&loginType=google" class="btn btn-primary btn-block login">Google Login </a></td></tr> 
            <tr><td><a class="btn btn-primary btn-block login " href="/signup/" >Sign Up</a> </td></tr> 
          </table>
         
        </div><!-- /card-container -->
    </div><!-- /container --> 
   
</form> 

