
<script src="/js/subjects.js"></script>

	<h1>Subject Records</h1>


	<?php if (empty($this->subjects)): ?>
			<div class="alert alert-info">No subject yet</div>
	<?php else: ?>
		
			<div class="col-md-6">
		
				<div id="subjects-pagination" class="pagination">
					  <ul class="pagination">
					    <li><a href="/subjects/index?page=<?php echo $this->currentPage <= 1?$this->currentPage=1:$this->currentPage-1; ?>">Prev</a></li>
					    <?php for ($pageNumber = 1; $pageNumber <= Subject::getNumberOfPages($this->subjectsCount); $pageNumber++) { ?>
					    	<li class="<?php echo ($pageNumber == $this->currentPage)?'active':'';?>"><a href="/subjects/index?page=<?php echo $pageNumber; ?>"><?php echo $pageNumber; ?></a></li>
					    <?php } ?>
					    <li><a href="/subjects/index?page=<?php echo ($this->currentPage >= Subject::getNumberOfPages($this->subjectsCount))?$this->currentPage:$this->currentPage+1; ?>">Next</a></li>
					  </ul>
				</div>
				<div>
					<a  
						class="pull-right btn btn-success" 
						title="add Subject"
						data-toggle="modal" data-target="#subject-add"
						> 
						<i class="glyphicon glyphicon-plus"></i>
					</a>
				</div>	
				<table class="table table-bordered table-condensed table-striped table-hover">
				<thead class="tHeader">
						<tr>
							<th>id</th>
							<th>subject</th>
							<th>lecUnit</th>
							<th>labUnit</th>
							<th>subjectUnit</th>
							<th>Details</th>
							<th>Edit</th>
							<th>Delete</th>
						</tr>	
				</thead>		
					<?php foreach ($this->subjects as $details):?>
				<tr >
					<td align="center" ><?php echo $details['subject_id']; ?></td> 
					<td align="center"><?php echo $details['subject']; ?></td>
					<td	align="center"><?php echo $details['lec_unit']; ?></td>
					<td	align="center"><?php echo $details['lab_unit']; ?></td>
					<td	align="center"><?php echo $details['subject_unit']; ?></td>
					<td>	
						<a 
							onclick="viewDetails(<?php echo $details['subject_id']; ?>);" 
							class="btn" 
							title="View Subject"
							data-toggle="modal" data-target="#subject-details"> 
							<i class="glyphicon glyphicon-search"></i>
						</a>
					</td>
					<td style="width: 1px; wrap: nowrap;">
					<!--	<a href="/subjects/edit?subject_id=<?php echo $details['subject_id']; ?>" 
							   class="btn" 
							   title="edit Subject"> 
							   <i class="icon icon-edit"></i>
						</a>-->
						<a 
							onclick="editSubject(<?php echo $details['subject_id']; ?>)" 
							class="btn" 
							title="edit Student"
							data-toggle="modal" data-target="#subject-edit"
							> 
							<i class="glyphicon glyphicon-edit"></i>
						</a>	
					</td>					
					<td style="width: 1px; wrap: nowrap;">			
						<a href='/subjects/delete?subject_id=<?php echo $details['subject_id']; ?>' 
									class="btn btn-danger" title="subject"> 
											<i class="glyphicon glyphicon-remove"></i>
										</a></td>

				</tr>
				<?php endforeach;?>
				</table>
			</div>
	<?php endif; ?>
	<div class="col-md-6">
		<h1>
		    <label class="label label-info">This is where you can view, edit, delete subjects</label>
		    <br></br>
		    <img id = "subject-img" class="second-slide" src="/img/subjects.jpg" alt="Second slide">
		</h1>
	</div>



<div id="subject-details" id="subjects" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Subject Details</h4>
      </div>
      <div class="modal-body">
        <dl>
        	<dt><label class="modal-label"> Subject ID: </label></dt><dd><input type="text" disabled id="subjectID" /></dd>
        	<dt><label class="modal-label"> Subject Name: </label></dt><dd><input type="text" disabled id="subjectName" /></dd>
        	<dt><label class="modal-label"> Subject Unit: </label></dt><dd><input type="text" disabled id="subjectUnit" /></dd>
        </dl>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i></button>
      </div>
    </div>

  </div>
</div>
<div id="subject-edit" id="subjects" class="modal fade" role="dialog">

	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 class="modal-title">Subject Edit</h4>
	      </div>
	      <div class="modal-body">
	      	<h1> Subject Edit </h1>

	        <dl>
	        	<dt><label class="modal-label"> Subject   ID : </label></dt><dd><input type="text" disabled id="editSubjectID" /></dd>
	        	<dt><label class="modal-label"> Subject      : </label></dt><dd><input type="text" id="editSubjectName" /></dd>
	        	<dt><label class="modal-label"> Subject Lec  : </label></dt><dd><input type="text" id="editSubjectLec" /></dd>
	        	<dt><label class="modal-label"> Subject Lab  : </label></dt><dd><input type="text" id="editSubjectLab" /></dd>
	        	<dt><label class="modal-label"> Subject Unit : </label> </dt><dd><input type="text" id="editSubjectUnit" /></dd>
	        </dl>
	      </div>
	      <div class="modal-footer">
	      	<button data-dismiss="modal" class="btn btn-default" id="button_save" type="submit" name="edit" value="save" onclick="updateSubject()">save</button>
	        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal">	<i class="glyphicon glyphicon-remove"></i></button>
	      </div>
	    </div>

	  </div>	
</div>
<div id="subject-add" id="subjects" class="modal fade" role="dialog">

	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 class="modal-title">Subject Add</h4>
	      </div>
	      <div class="modal-body">
	      	<h1> Subject Edit </h1>

	        <dl>
	        	<dt><label class="modal-label"> Subject      : </label></dt><dd><input type="text" id="addSubjectName" /></dd>
	        	<dt><label class="modal-label"> Subject Lec  : </label><dd><input type="text" id="addSubjectLec" /></dd>
	        	<dt><label class="modal-label"> Subject Lab  : </label><dd><input type="text" id="addSubjectLab" /></dd>
	        	<dt><label class="modal-label"> Subject Unit : </label> </dt><dd><input type="text" id="addSubjectUnit" /></dd>
	        </dl>
	      </div>
	      <div class="modal-footer">
	      	<button data-dismiss="modal" class="btn btn-default" id="button_save" type="submit" name="edit" value="save" onclick="addSubject()">save</button>
	        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal">	<i class="glyphicon glyphicon-remove"></i></button>
	      </div>
	    </div>

	  </div>	
</div>
</nav>
