
<form  method ="POST">
<nav id ="searchStudent">
	<div id="container"> 
		<h1>Add User</h1>

		<h3 id="input"></h3>
		<input type="text" name="username" " value="<?php echo $this->admin['username']; ?>" /> User Name<br/>
		<input type="text" name="password" " value="<?php echo $this->admin['password']; ?>"/>  Password<br/> 
		
		<input class="btn" id="button_save" type="submit" name="save" value="save" />		
		<a style="float:right" href="/Admin">(Return)</a>
	</div>
</nav>	
</form>

